### ISSUE TITLE
Userdata Properties

### ISSUE THREAD

**Issue by JoelBrd** [csqrl/codify-plugin#22]
![image](https://user-images.githubusercontent.com/38959456/166333499-2d3a01af-0818-4858-a0e2-6b397954a798.png)
I've only noticed this with `FontFace`; will try populate some property fields with userdata.

Somewhat linked to issue #18

**Comment by csqrl** [comment]
Thanks for the feedback! I've issued a hotfix in v2.2.3 to address this issue. This adds the ability to internally filter out useless properties such as these, that should've probably been hidden by Roblox until they're ready.

**Comment by csqrl** [comment]
**Update:** `v2.2.4-patch.2` now filters out the `Font` property in favour of `FontFace`, which uses a new `Font` datatype to describe the font being used.
