### ISSUE TITLE
Add a option to keep instance names the same as the original ones

### ISSUE THREAD

**Issue by RealEthanPlayzDev** [csqrl/codify-plugin#23]
There is no way to keep instance names the same as they were as the original version
![image](https://user-images.githubusercontent.com/30568955/168553399-c2b2e2fa-46dd-417d-afa3-5af0d38e54e3.png)

![image](https://user-images.githubusercontent.com/30568955/168553291-a7dbc7f2-607d-45e7-9fe7-6511332b44cf.png)
![image](https://user-images.githubusercontent.com/30568955/168553312-e0cf6da4-46dc-4a85-9f30-4549b8f67247.png)

**Comment by csqrl** [comment]
Are you requesting that the `.Name` property keeps the same casing as the original Instance, or the variable name should follow the same casing?

**Comment by csqrl** [comment]
gotcha! this should be resolved in the most newest version. it'd previously been set to the "safe name" generated for the variable names. bit of an oversight there
