### ISSUE TITLE
invalid argument #1 to 'find' (table expected, got string)

### ISSUE THREAD

**Issue by RealEthanPlayzDev** [csqrl/codify-plugin#24]
This is happenning to me, no matter what framework I chose, it returns this error as a warning on the output
```
Regular:
  21:35:26.491  cloud_4749111907.CodifyPlugin.Lib.Codify.Frameworks.Regular:30: invalid argument #1 to 'find' (table expected, got string)  -  Edit

Fusion:
  21:37:28.167  cloud_4749111907.CodifyPlugin.Lib.Codify.Frameworks.Fusion:22: invalid argument #1 to 'find' (table expected, got string)  -  Edit

Roact:
  21:39:03.696  cloud_4749111907.CodifyPlugin.Lib.Codify.Frameworks.Roact:44: invalid argument #1 to 'ipairs' (table expected, got string)  -  Edit
```

Reproduction steps:
- Create a TextLabel (not sure on other GuiObjects, tested on a TextLabel)
- Use Codify and attempt to generate a snippet

**Comment by csqrl** [comment]
I'm unable to reproduce this issue using the steps provided. Could you ensure you're using the latest version of Codify, and if the problem persists, attach a repro file for this issue?

**Comment by RealEthanPlayzDev** [comment]
Turning off the Cloudflare WARP VPN temporarily solved it
