### ISSUE TITLE
`inf` Is Not Converted As A Valid Type

### ISSUE THREAD

**Issue by christopher-buss** [csqrl/codify-plugin#27]
I have a UISizeConstraint that currently had a max X size of "inf", and a min Y size of 85, as I did not care in this case how big the X size was.

I'd expect codify to convert inf to math.huge, but instead, it just left it in code as "inf", which is not a recognisable lua type.

**Comment by csqrl** [comment]
This has been addressed in the unofficial `v2.2.4-patch.1` patch. I will close this issue when `v2.3.0` is released, since this issue is still present in the current GitHub source.
