### ISSUE TITLE
Codify hits max length

### ISSUE THREAD

**Issue by supercoolspy** [csqrl/codify-plugin#31]
Hi, I think codify has a max length when I try to generate large objects. It only generates half.

Example: https://pastes.dev/o6X8V5Nzcc

**Comment by csqrl** [comment]
You're correct. This is a limit on Roblox's side. Roblox TextBoxes will only render so much before they cut off the contents.

If you're hitting the maximum length, that should tell you you need to split into smaller components, or use the "Save to Device" button, which will allow you to export the snippet straight to your device.

From there you can either open it with a program like Notepad or vscode, or reimport it back into Studio by right-clicking in the Explorer and choosing "Insert from File..."

However, I plan on making it obvious in the next major release that your code has been truncated, and will make options to export more prominent in this scenario.
